### ISSUE TITLE
Aggiungere nuove get request per la pagina delle statistiche

### ISSUE THREAD

**Issue by Loryyyy007** [TriDevz/Silamena-API#7]
1. GET "api/words/role-amount/:role" -> ti da il numero di parole che hanno un certo role. Body: {"count": count}
2. GET "api/words/recent-additions?days=..." -> ti da il numero di parole aggiunte negli ultimi days giorni (def 7). Body: {"count": count}
3. GET "api/examples/amount" -> ti da il numero totale di esempi (come "examples/all" ma senza gli esempi). Body: {"count": count}

**Comment by emyst01** [comment]
fatto
